apiVersion: apps/v1
kind: Deployment
metadata:
  name: shanari-shanari-deployment
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      terminationGracePeriodSeconds: 25
      containers:
        - name: shanari-shanari-fe
          image: asia-northeast1-docker.pkg.dev/shanari-shanari/shanari-shanari/shanari-shanari-fe:bfbdf1f9a9d9f67131e19e1e86ce9347d667839c
