apiVersion: apps/v1
kind: Deployment
metadata:
  name: shanari-shanari-deployment
spec:
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/ephemeral-storage-limit: 15Gi
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
        cloud.google.com/gke-ephemeral-storage-local-ssd: "true"
      terminationGracePeriodSeconds: 30
      containers:
        - name: shanari-shanari-fe
          image: asia-northeast1-docker.pkg.dev/shanari-shanari/shanari-shanari/shanari-shanari-fe:830a08e210562e8a17525340e86e1faab8b6df79
          volumeMounts:
            - name: gcs-fuse-csi-ephemeral
              mountPath: /app/public/contents/blog/
              readOnly: false
      serviceAccountName: shanari-ksa
      volumes:
        - name: gcs-fuse-csi-ephemeral
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: false
            volumeAttributes:
              bucketName: shanari-blog-posts
              mountOptions: "implicit-dirs,uid=1001,gid=1001,file-mode,dir-mode"
              gcsfuseLoggingSeverity: error
              fileCacheCapacity: "10Gi"
              metadataCacheTTLSeconds: "3600"
