apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shanari-shanari-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: shanari-shanari-ip
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
  labels:
    app: shanari-shanari
spec:
  defaultBackend:
    service:
      name: shanari-shanari-service
      port:
        number: 80
