apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - managed-cert.yaml
  - persistent-volume.yaml
  - persistent-volume-claim.yaml
patches:
  - path: deployment.yaml
  - path: service.yaml
