apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-fuse-csi-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 50Gi
  storageClassName: shanari-storage-class
  mountOptions:
    - uid=1001
    - gid=1001
    - file-mode=755
    - dir-mode=755
    - implicit-dirs
    - stat-cache-capacity=102400
    - stat-cache-ttl=3600s
    - type-cache-ttl=3600s
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: shanari-blog-posts
    volumeAttributes:
      gcsfuseLoggingSeverity: error
      fileCacheCapacity: 1Gi
      fileCacheForRangeRead: "true"
      metadataStatCacheCapacity: 32Mi
      metadataTypeCacheCapacity: 4Mi
