apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-fuse-csi-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  storageClassName: shanari-storage-class
  mountOptions:
    - uid=1001
    - gid=1001
    - file-mode
    - dir-mode
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: shanari-blog-posts
    volumeAttributes:
      gcsfuseLoggingSeverity: warning
