apiVersion: v1
kind: Service
metadata:
  name: shanari-shanari-service
  labels:
    app: shanari
spec:
  selector:
    app: shanari-shanari
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
