apiVersion: apps/v1
kind: Deployment
metadata:
  name: shanari-shanari-fe-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shanari-shanari-fe
  template:
    metadata:
      labels:
        app: shanari-shanari-fe
    spec:
      imagePullSecrets:
        - name: argocd-gcp-secret
      containers:
        - name: shanari-shanari-fe
          image: asia-northeast1-docker.pkg.dev/shanari-shanari/shanari-shanari/shanari-shanari-fe:277818ca3aa3eaf96dc6542bb11cb1367831251b
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
